SELECT SUM(gr.SCORE) AS SCORE
    , gr.EMP_NO
    , em.EMP_NAME
    , em.POSITION
    , em.EMAIL
FROM HR_DEPARTMENT dp
    LEFT JOIN HR_EMPLOYEES em
    ON dp.DEPT_ID = em.DEPT_ID
    LEFT JOIN HR_GRADE gr
    ON em.EMP_NO = gr.EMP_NO
WHERE gr.YEAR = 2022
GROUP BY 2,3,4,5
ORDER BY 1 DESC
LIMIT 1;