SELECT NAME
    , DATETIME
FROM (
    SELECT ai.NAME
        , ai.DATETIME
        , ROW_NUMBER() OVER (ORDER BY ai.DATETIME ASC) AS rn
    FROM ANIMAL_INS ai
        LEFT JOIN ANIMAL_OUTS ao
        ON ai.ANIMAL_ID = ao.ANIMAL_ID
    WHERE ao.ANIMAL_ID IS NULL
) a
WHERE rn <= 3
ORDER BY DATETIME ASC