SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM (
    SELECT b.BOARD_ID, f.FILE_ID, f.FILE_NAME, f.FILE_EXT
        , RANK() OVER(ORDER BY b.VIEWS DESC) AS 'RANK'
    FROM USED_GOODS_BOARD b
        INNER JOIN USED_GOODS_FILE f
            ON b.BOARD_ID = f.BOARD_ID
) a
WHERE `RANK` = 1
ORDER BY FILE_ID DESC