SELECT i2.ITEM_ID
    , i2.ITEM_NAME
    , i2.RARITY
FROM ITEM_INFO i
    INNER JOIN ITEM_TREE t ON i.ITEM_ID = t.PARENT_ITEM_ID
    INNER JOIN ITEM_INFO i2 ON t.ITEM_ID = i2.ITEM_ID
WHERE i.RARITY = 'RARE'
ORDER BY i2.ITEM_ID DESC;