SELECT hd.DEPT_ID
    , hd.DEPT_NAME_EN
    , ROUND(AVG(he.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT hd
    INNER JOIN HR_EMPLOYEES he
        ON hd.DEPT_ID = he.DEPT_ID
GROUP BY 1, 2
ORDER BY AVG_SAL DESC;
